@host = http://localhost:2022

GET {{host}}
Accept: application/json

### POST Tareas

POST {{host}}/tareas
Content-Type: application/json

{
    "Id": 14,
    "Titulo": "Prueba",
    "Completada": false

}
### Get Todas las tareas
GET {{host}}/tareas
Accept: application/json

### Get Una tarea
GET {{host}}/tareas/12
Accept: application/json

### Delete

DELETE {{host}}/tareas/12


###
